# [START app_yaml]
runtime: nodejs14

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

handlers:
- url: /.*
  secure: optional
  script: auto
  
# [END app_yaml]